learning_site/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'html/(?P<course_pk>\d+)/(?P<step_pk>\d+)$',
        views.step_detail,
        name='step'),
    url(r'html/(?P<pk>\d+)/$',
        views.course_detail,
        name='detail'),
    url(r'api/v1/courses/$',
        views.ListCreateCourse.as_view(),
        name='api_course_list'),
    url(r'api/v1/courses/(?P<pk>[0-9]+)/$',
        views.RetrieveUpdateDestroyCourse.as_view(),
        name='api_course_detail'),
    url(r'^api/v1/courses/(?P<course_pk>[0-9]+)/steps/$',
        views.ListCreateStep.as_view(),
        name='api_step_list'),
    url(r'^api/v1/courses/(?P<course_pk>[0-9]+)/steps/(?P<pk>[0-9]+)/$',
        views.RetrieveUpdateDestroyStep.as_view(),
        name='api_step_detail'),
]

learning_site/learning_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.hello_world),
    # create link to django built-in api authentication
    # to gain access, run "python manage.py createsuperuser"
    # to access, navigate to localhost:8000/api-auth/login
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    # related name defines a name for the many-to-one relationship
    course = models.ForeignKey(Course, related_name='steps')

    class Meta:
        ordering = ['order',]
        # this specifies that together, these fields must create a unique key
        unique_together = ['title', 'course']

    def __str__(self):
        return self.title

learning_site/courses/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404, render
from rest_framework import status, generics, viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from . import serializers, models

from .models import Course, Step

# NOTE: Access browsable API at http://localhost:8000/courses/api/v1/courses


# NOTE: API using generic views
class ListCreateCourse(generics.ListCreateAPIView):
    queryset = models.Course.objects.all()
    serializer_class = serializers.CourseSerializer

class RetrieveUpdateDestroyCourse(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Course.objects.all()
    serializer_class = serializers.CourseSerializer

class ListCreateStep(generics.ListCreateAPIView):
    queryset = models.Step.objects.all()
    serializer_class = serializers.StepSerializer

    # override get method of generics
    def get_queryset(self):
        return self.queryset.filter(course_id=self.kwargs.get('course_pk'))

    # This is the method that is run right when an object is
    # being created by the view. We override it in order to disallow
    # the user from creating a step for an arbitrary course.
    def perform_create(self):
        course = get_object_or_404(
            models.Step, pk=self.kwargs.get('course_pk'))
        serializer.save(course=course)

class RetrieveUpdateDestroyStep(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Step.objects.all()
    serializer_class = serializers.StepSerializer

    # like get_query_set, but returns a single item.
    def get_object(self):
        course = models.Course.objects.filter(pk=self.kwargs.get('course_pk'))
        return get_object_or_404(
            self.get_queryset(),
            course=course,
            pk=self.kwargs.get('pk')
        )

# # NOTE: API V2
# class CourseViewSet(viewsets.ModelViewSet):
#     queryset = models.Course.objects.all()
#     serializer = serializers.CourseSerializer
#
# class StepViewSet(viewsets.ModelViewSet):
#     queryset = models.Step.objects.all()
#     seializer = serializers.StepSerializer


# NOTE: API using non-generic view
# class ListCreateCourse(APIView):
#     def get(self, request, format=None):
#         courses = models.Course.objects.all()
#         serializer = serializers.CourseSerializer(courses, many=True)
#         return Response(serializer.data)
#
#     def post(self, request, format=None):
#         serializer = serializers.CourseSerializer(data=request.data)
#         # checks to make sure incoming data passes validation
#         # checks/rules provided in the model
#         serializer.is_valid(raise_exception=True)
#         # saves to database and updates serializer fields with
#         # database provided fields, such as 'created_at'.
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_201_CREATED)

# Templates
def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})

def course_detail(request, pk):
    # course = Course.objects.get(pk=pk) # without 404, conventional way
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_site/learning_site/views.py
from django.shortcuts import render

def hello_world(request):
    return render(request, 'home.html')

learning_site/courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<article>
  <h2>{{ course.title }}</h2>
  {{ course.description }}

  <section>
    {% for step in course.step_set.all %}
       <h3>
         <a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a>
       </h3>
       {{ step.description }}
    {% endfor %}
  </section>
</article>
{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% extends "layout.html" %}

{% block title %}Available Courses{% endblock %}

{% block content %}
  <div class="cards">
    {% for course in courses %}
    <div class="card">
      <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title}}</a></header>
      <div class="card-copy">
        {{ course.description}}
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

learning_site/courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %}
  {{ step.title }} - {{ step.course.title }}
{% endblock %}

{% block content %}
  <article>
    <h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
    <h3>{{ step.title }}</h3>
    {{ step.content|linebreaks }}
  </article>
{% endblock %}

learning_site/templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

learning_site/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  </head>
  <body>
    <div class="site-container">
      <nav>
        <a href="{% url 'courses:list' %}">Home</a>
      </nav>
    </div>
    <div class="site-container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>